global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.20.28:8080']

  - job_name: 'prometheus-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '192.168.20.28:9090' ]